// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSQ8ve79Ab3UlHt7QjjmodA8cS0Vgeiv4',
    appId: '1:573164061727:web:b6b90c6ebf8622cd74812a',
    messagingSenderId: '573164061727',
    projectId: 'ecommerceproject-9e494',
    authDomain: 'ecommerceproject-9e494.firebaseapp.com',
    storageBucket: 'ecommerceproject-9e494.appspot.com',
    measurementId: 'G-D8R6SE1VVM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpMxwnXBAUdvUgUPR7VKIv2VXS80n4eSY',
    appId: '1:573164061727:android:3c76003bafd3c2d074812a',
    messagingSenderId: '573164061727',
    projectId: 'ecommerceproject-9e494',
    storageBucket: 'ecommerceproject-9e494.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXhZX2-cV96pfLKMclVkbrZpgGlSpaFWw',
    appId: '1:573164061727:ios:bb79e14e4dc4952574812a',
    messagingSenderId: '573164061727',
    projectId: 'ecommerceproject-9e494',
    storageBucket: 'ecommerceproject-9e494.appspot.com',
    iosBundleId: 'com.example.eComProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXhZX2-cV96pfLKMclVkbrZpgGlSpaFWw',
    appId: '1:573164061727:ios:bb79e14e4dc4952574812a',
    messagingSenderId: '573164061727',
    projectId: 'ecommerceproject-9e494',
    storageBucket: 'ecommerceproject-9e494.appspot.com',
    iosBundleId: 'com.example.eComProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSQ8ve79Ab3UlHt7QjjmodA8cS0Vgeiv4',
    appId: '1:573164061727:web:f1b001a0ca1ef76f74812a',
    messagingSenderId: '573164061727',
    projectId: 'ecommerceproject-9e494',
    authDomain: 'ecommerceproject-9e494.firebaseapp.com',
    storageBucket: 'ecommerceproject-9e494.appspot.com',
    measurementId: 'G-9QC34FSSV7',
  );
}
